export const transactions = [
    {
        id: 1,
        title: "Netflix",
        date: "2021-01-01",
        amount: 8.99,
        category: "Subscription",
        type: "Expense",
    },
    {
        id: 2,
        title: "Paypal",
        date: "2021-01-02",
        amount: 120,
        category: "Transfer",
        type: "Expense",
    },
    {
        id: 3,
        title: "Joe Biden",
        date: "2021-01-10",
        amount: 85.50,
        category: "Bank Transfer",
        type: "Income",
    },
    {
        id: 4,
        title: "Spotify",
        date: "2021-01-15",
        amount: 9.99,
        category: "Subscription",
        type: "Expense",
    },
    {
        id: 5,
        title: "Grocery Store",
        date: "2021-01-20",
        amount: 45.60,
        category: "Groceries",
        type: "Expense",
    },
    {
        id: 6,
        title: "Amazon",
        date: "2021-01-25",
        amount: 29.99,
        category: "Shopping",
        type: "Expense",
    },
    {
        id: 7,
        title: "Salary",
        date: "2021-01-30",
        amount: 2500,
        category: "Salary",
        type: "Income",
    },
    {
        id: 8,
        title: "Electricity Bill",
        date: "2021-02-05",
        amount: 60.00,
        category: "Utilities",
        type: "Expense",
    },
    {
        id: 9,
        title: "Restaurant",
        date: "2021-02-10",
        amount: 75.20,
        category: "Dining",
        type: "Expense",
    },
    {
        id: 10,
        title: "Freelance Project",
        date: "2021-02-15",
        amount: 500,
        category: "Freelance",
        type: "Income",
    },
    {
        id: 11,
        title: "Gym Membership",
        date: "2021-02-20",
        amount: 30.00,
        category: "Subscription",
        type: "Expense",
    },
    {
        id: 12,
        title: "Car Maintenance",
        date: "2021-02-25",
        amount: 150.00,
        category: "Automobile",
        type: "Expense",
    },
    {
        id: 13,
        title: "Dividends",
        date: "2021-03-01",
        amount: 200.00,
        category: "Investments",
        type: "Income",
    },
    {
        id: 14,
        title: "Bookstore",
        date: "2021-03-05",
        amount: 40.50,
        category: "Shopping",
        type: "Expense",
    },
    {
        id: 15,
        title: "Online Course",
        date: "2021-03-10",
        amount: 99.00,
        category: "Education",
        type: "Expense",
    },
];
